feature: Add enabled property to patterns.json
codacy/codacy-tsqllint pull request #23
Opened 2020-09-15 10:13 UTC by franciscodua

2020-09-15 11:25 UTC, lolgab requested changes

2020-09-15 11:25 UTC, lolgab commented on src/DocsGenerator/Helpers/DefaultPatterns.cs
> +}
A newline here

2020-09-15 12:33 UTC, franciscodua commented on src/DocsGenerator/Helpers/DefaultPatterns.cs
> +}
Done

2020-09-15 16:36 UTC, josemiguelmelo approved these changes

2020-09-16 08:05 UTC, lolgab approved these changes
Thank you 😊

2020-09-16 10:30 UTC, merged